version: '3'

services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: example_user
      POSTGRES_PASSWORD: example_password
      POSTGRES_DB: example_db
    ports:
      - "5432:5432"
    expose:
      - "5432"
    networks:
      - postgres
  
  web-node:
    container_name: web-node
    image: web
    working_dir: /code
    build:
      context: .
      dockerfile: web/Dockerfile
    command: uvicorn web.main:app --host 0.0.0.0 --port 5020 --reload
    environment:
      DEBUG: 1
    volumes:
      - .:/code
    ports:
      - "5020:5020"
    expose:
      - "5020"
    restart: on-failure
    depends_on:
      - "db"
    networks:
      - postgres

networks:
  postgres:
    driver: bridge
